### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by karpadiem** [mrothenbuecher/zpl-rest#1]
Hey There!

Really excited about using this! It seems to be EXACTLY what we need and is making this process so much easier. However, one thing we are having issues with is special characters. When added directly to the template they print just fine. However, when contained in the json they seem to be getting reformatted before being applied via mustache. I'm trying to find where this might happen in the code, but im not really a Node pro.

Any ideas on how to fix?

**Comment by karpadiem** [comment]
Changed my placeholders from mustache {{varName}} to ${varName} and the formatting fixed!

So, yeah, seems like something is mustache is adding an extra layer of special character encoding to it.

**Comment by mrothenbuecher** [comment]
Thanks for the feedback!

You also could try {{{varName}}} [(see)](https://stackoverflow.com/questions/12834419/text-as-html-in-mustache-js).
