### ISSUE TITLE
Print label multiple times

### ISSUE THREAD

**Issue by Maytrok** [mrothenbuecher/zpl-rest#15]
Hello,

I plan to use this project in our company as middleware between our CMS and the printer.

We need to print a label multiple times (30-50) in a row. I didn't find an option to define the print quantity.

Am I blind or is there no such option? What is the best approach here?

**Comment by nvschilleman** [comment]
Hi there,

You can add ^PQ followed by a variable to your ZPL code and send the quantity along with the rest of your variables in the API request. 

See https://stackoverflow.com/questions/45621272/zebra-zpl-code-repeat-label-x-times

**Comment by Maytrok** [comment]
hi,

yeah i found that command the same day and forgot to close the issue. Thanks for the response
